### PR TITLE
Update zhTW/zhCN

### PR DESCRIPTION
**Pull request by EKE00372**
There are some note in file, hope every options and tips have their full entry for translate, or will make a bad grammar in Asian launguage, even will lost punctuation.

Some entry are repeat, so i skip them.

Qty and lvl will invisible in Asian client after translate, because they don't have enough space.

I think this can directly used on both retail and classic version, have test in game already.

### CODE REVIEW

**Comment by pwilkowski** [comment]
Did you check if it works? Some fixes will be required as 3rd parameter cannot be true (it makes default locale)

**Comment by EKE00372** [comment]
You mean there are still some "true" in locales? Some of them are half sentence so need more think, some of them won't be hinder when use, I didn't translate because still thinking better translate.

**Comment by EKE00372** [comment]
Some notes when i translate:

1. possible need a unified format for addon name(Auction Faster or AuctionFaster), I use 'Auction Faster', with space in middle

2. L[' stack size: '] = '组出售，每组堆叠'	
this will make bad grammar in un-latin locale such like asian. 
suggest better way is : ' %s stack, size: %s' then can be translate as '%2$s组，每组%1$s个' 
L['Pages: '] = '页：'	-- same, better is "Pages %s" so can translate as "第%s页"
if no plan to change format, it's ok now because i didn't translate word by word, just use another way (in other words) try match this entry mean.

3. L['Stack Size (Max: '] = '堆叠（最大：'	-- the better way hould be 'Stack Size (Max: %s)'
lost a ")" is not good....also, the ")" in chinese is "）", a little different.

4. Word order are different between english and chinese. it will be strange if use english world order.
for example:
L['Your price will be overriden'] = '你的价格会被复盖'
L['if "Always Undercut" options is checked!'] = '，如果勾选了“总是自动压价”'

no matter how, thanks your read!

**Comment by pwilkowski** [comment]
Yeah you are right i need to make some sprinfts so translation is consistent

**Comment by EKE00372** [comment]
You can merge straightway if you are willing to do this, I'll update others later x.x

**Comment by pwilkowski** [comment]
Ok then, I'll merge it but we will need some changes soon after because i will be going with sprintfs
 (so that you can use %s in messages)

**Comment by EKE00372** [comment]
sure i'll fallow update! ty

**Comment by pwilkowski** [comment]
I just pushed update, consolidated a lot of strings. Also, **feel free to change code** if I forgot to transform localization to use sprint (string.format).

basically put 
`local format = string.format;`
At the top of file (if it isn't there already)

and use it like this `format(L['Some string %s'], 'string')`

**Comment by EKE00372** [comment]
Thank you, working on it!

**Comment by EKE00372** [comment]
#68 ready!

**Pull request merged**
